[project]
name = "appwrite-reflex-template"
version = "0.1.0"
description = "Full Appwrite & Reflex App Template"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "pydantic-settings>=2.0.0",
    "python-dotenv>=1.2.1",
    "reflex>=0.8.24.post1",
]
